baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "hugo-journal"

[params]
  description = "Blog meta description."
  githubUsername = "simaung"
  twitterUsername = "ddhr00"
  tagline = "Berbagi itu indah"
[params.work]
  jobTitle = "Programmer"
  company = "Asia Digital Indonesia"
  companyUrl = "https://asiadigitalindonesia.com"
# [params.gpg]
#   key = "0x1111111111111111"
#   fingerprint = "0000 0000 0000 0000 0000  0000 0000 0000 0000 0000"
#   link = "https://pgp.mit.edu/pks/lookup?op=get&search=0x1111111111111111"

